apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gapplication
  template:
    metadata:
      labels:
        app: gapplication
    spec:
      containers:
      - name: gcontainer
        image: tomcat:9-jdk17
